data:
  name: 'Burgers'
  datapath: 'dataset/burgers_pino.mat'
  total_num: 1000
  offset: 0
  n_sample: 800
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
  padding: 0 
  pde_sub: 1
  pde_sub_t: 1
  pde_padding: 0

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  activation: gelu

train:
  batchsize: 5
  epochs: 500
  milestones: [150, 300, 450]
  base_lr: 0.001
  scheduler_gamma: 0.5  z
  ic_loss: 10.0
  f_loss: 1.0
  xy_loss: 0
  save_dir: 'burgers-FDM'
  save_name: 'burgers-pretrain-eqn.pt'

log:
  project: 'PINO-burgers-pretrain'
  group: 'gelu-eqn'
  entity: kamyara


