data:
  name: 'Darcy'
  datapath: '/raid/hongkai/darcy-train.mat'
  total_num: 1024
  offset: 0
  n_sample: 1000
  nx: 421
  padding: 4 
  sub: 7
  pde_padding: 14 
  pde_sub: 2

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  fc_dim: 128
  activation: gelu

train:
  batchsize: 1
  epochs: 300
  milestones: [100, 150, 200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'darcy-FDM'
  save_name: 'darcy-pretrain-pino.pt'

log:
  project: 'PINO-Darcy-pretrain'
  group: gelu-pino
  entity: hzzheng-pino 

