wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1664833743.696573
    t:
      1:
      - 1
      - 55
      - 76
      2:
      - 1
      - 55
      - 76
      3:
      - 15
      - 16
      - 23
      4: 3.10.4
      5: 0.13.1
      8:
      - 6
data:
  desc: null
  value:
    datapath: dataset/piececonst_r421_N1024_smooth1.mat
    n_sample: 1000
    name: Darcy
    nx: 421
    offset: 0
    padding: 4
    pde_padding: 28
    pde_sub: 1
    sub: 7
    total_num: 1024
log:
  desc: null
  value:
    entity: kamyara
    group: gelu-pino
    project: PINO-Darcy-pretrain
model:
  desc: null
  value:
    activation: gelu
    fc_dim: 128
    layers:
    - 64
    - 64
    - 64
    - 64
    - 64
    modes1:
    - 20
    - 20
    - 20
    - 20
    modes2:
    - 20
    - 20
    - 20
    - 20
train:
  desc: null
  value:
    base_lr: 0.001
    batchsize: 1
    epochs: 300
    f_loss: 1.0
    milestones:
    - 100
    - 150
    - 200
    save_dir: darcy-FDM
    save_name: darcy-pretrain-pino.pt
    scheduler_gamma: 0.5
    xy_loss: 5.0
