wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1665505500.291108
    t:
      1:
      - 1
      - 55
      - 76
      2:
      - 1
      - 55
      - 76
      3:
      - 15
      - 16
      - 23
      4: 3.10.4
      5: 0.13.1
      8:
      - 6
data:
  desc: null
  value:
    datapath: dataset/burgers_pino.mat
    n_sample: 800
    name: Burgers
    nt: 100
    nx: 128
    offset: 0
    padding: 0
    pde_padding: 0
    pde_sub: 1
    pde_sub_t: 1
    sub: 1
    sub_t: 1
    total_num: 1000
log:
  desc: null
  value:
    entity: kamyara
    group: gelu-eqn
    project: PINO-burgers-pretrain
model:
  desc: null
  value:
    activation: gelu
    fc_dim: 128
    layers:
    - 16
    - 24
    - 24
    - 32
    - 32
    modes1:
    - 15
    - 12
    - 9
    - 9
    modes2:
    - 15
    - 12
    - 9
    - 9
train:
  desc: null
  value:
    base_lr: 0.001
    batchsize: 5
    epochs: 500
    f_loss: 1.0
    ic_loss: 10.0
    milestones:
    - 150
    - 300
    - 450
    save_dir: burgers-FDM
    save_name: burgers-pretrain-eqn.pt
    scheduler_gamma: 0.5  z
    xy_loss: 0
